name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-version: ['8.1', '8.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, openssl, json
      - run: composer install --no-interaction --no-progress
      - run: php vendor/bin/phpunit
